# Generated by Django 3.2.12 on 2024-01-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration', models.CharField(max_length=100)),
                ('ship_class', models.CharField(max_length=100)),
                ('captain', models.CharField(max_length=100)),
            ],
        ),
    ]
