# Generated by Django 3.2.12 on 2024-01-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='maintenance date')),
                ('work', models.CharField(choices=[('W', 'Warp Core'), ('S', 'Shields'), ('T', 'Transporters')], default='W', max_length=1)),
                ('starship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.starship')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
